name: quantum_decoder
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - requests
  - prody
  - biopython
  - openmm
  - pdbfixer
  - rdkit
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-geometric
  - scikit-learn
  - networkx
  - pip
  - pip:
    - kaggle
    - graphein
    - torch-scatter
    - torch-sparse
    - pyg-lib
    - pyyaml
    - tqdm
    - plotly
    - pillow
